### ISSUE TITLE
`to': wrong number of arguments

### ISSUE THREAD

**Issue by semireg** [seamusabshere/conversions#1]
I'm new to ruby and I want to play around with conversions.  However, I can't get it to work correctly.

$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.2.0]

$ gem install conversions
Fetching: conversions-1.4.6.gem (100%)
Successfully installed conversions-1.4.6
1 gem installed

$ cat test.rb 
require 'conversions'   

puts 5.miles.to.kilometers

$ ruby test.rb 
/Users/i/.rvm/gems/ruby-1.9.3-p327/gems/conversions-1.4.6/lib/conversions/unit.rb:26:in `to': wrong number of arguments (0 for 1) (ArgumentError)
    from test.rb:3:in`<main>'

It seems that lib/conversions/default_table.rb is missing or incomplete.

$ cat /Users/i/.rvm/gems/ruby-1.9.3-p327/gems/conversions-1.4.6/lib/conversions/defaults.rb 
{
  :miles => {
    :kilometres => 1.609344
  },
  :kilograms => {
    :grams => 1000.0,
    :pounds => 2.20462262,
    :short_tons => 0.00110231131,
    :tons => 0.00110231131
  },
  :tons => {
    :pounds => 2000.0
  },
  :gallons => {
    :litres => 3.7854118
  },
  :cubic_feet => {
    :cubic_meters => 0.0283168466
  },
  :miles_per_gallon => {
    :kilometres_per_litre => 0.425143707
  }
}.each do |from_unit, to_units|
  to_units.each do |to_unit, rate|
    Conversions.register(from_unit, to_unit, rate)
  end

**Comment by seamusabshere** [comment]
`5.miles.to(:kilometres)` ?

**Comment by semireg** [comment]
Thanks, seamusabshere.  Is object chaining broken intentionally?  The default exchange rate table is woefully empty...

1.9.3-p327 :006 > 5.miles.to(:kilometers)
ArgumentError: [conversions] No exchange rate defined from `miles' to`kilometers'
    from /Users/i/.rvm/gems/ruby-1.9.3-p327/gems/conversions-1.4.6/lib/conversions/unit.rb:43:in `exchange_rate'
    from /Users/i/.rvm/gems/ruby-1.9.3-p327/gems/conversions-1.4.6/lib/conversions/unit.rb:34:in`to'
    from (irb):6
    from /Users/i/.rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'

Madison, WI?  I'm in Winona, MN.  I lived in Madison from 2006-2009.

**Comment by seamusabshere** [comment]
re: object chaining, it's "broken" to keep it simple - it's worked for us so far.

re: `kilometres` vs `kilometers` - we go with the ISO/British spelling.

re: default exchange rate table, agreed, it's pretty bare. lots of useless ones can be found in https://github.com/brighterplanet/earth/blob/master/lib/earth/conversions_ext.rb though :)

I'm from Madison and just moved back in 2010 - glad to be home!
